server:
  port: 8082

spring:
  DataSource:
    url: jdbc:mysql://localhost:3306/lin-cms?charactorEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true

  thymeleaf:
    prefix: classpath:/public/template/
  redis:
    port: 6379
    host: localhost
    database: 7
    listen-pattern: __keyevent@7__:expired
spring.resources.static-locations: classpath:/public/template/
spring.mvc.static-path-pattern: /public/**
spring.jpa.hibernate.ddl-auto: create
mybatis:
  #typeAliasesPackage: org.cv.sf.repository.mybatis
  mapperLocations: classpath:mapper/*.xml
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true

#log4j.rootLogger : INFO, DebugFile,Console, LogFile, ErrorFile

## Disable other log
#log4j.logger.org.mybatis=OFF
#log4j.logger.com.yqbsoft.laser=OFF
#log4j.logger.org.springframework=OFF
#log4j.logger.com.ibatis=OFF
#log4j.logger.org.spring=OFF
#log4j.logger.Java.sql.Connection=OFF
#log4j.logger.java.sql.Statement=OFF
#log4j.logger.java.sql.PreparedStatement=OFF



